# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8950ca00d3cb88d6339103bfe48f4eaa4bce6af4d6d342af35a5345b665ee07073cc1539f4ee0705edd836338d6867d1a9f77f9113e9aef1d10796713ddc60d3

test:
  secret_key_base: 6bf14e8b250e12ef8d05f9b4dfba28a75dd8acf5656ddda9f9b707460a3030c56cced67a9272199da5aec1e6a98f2b8edbbeaeb176ca98fbca794fae3ade856a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
